Add Button; Add Text; Fix box model
AmyGrooove/bisky-front pull request #5
Opened 2024-02-26 12:18 UTC by BlackPoretsky

2024-02-26 18:56 UTC, AmyGrooove requested changes

2024-02-26 18:56 UTC, AmyGrooove commented on src/shared/ui/atoms/Text/Types/ITextProps.ts
> +  children: string
если children не опционален, то получается, нельзя создать компонент чисто с иконкой (сделай его просто опциональным)

2024-02-27 07:30 UTC, BlackPoretsky commented on src/shared/styles/mixins/defineFontSize.scss
С тем, что в reusable они не нужны я согласен, но "без mixins внутри" ты хочешь просто перечислением сделать?
И зачем тогда уже создавать отдельную папку? Тогда просто можно в Text.module.scss уже это написать.

2024-02-27 07:31 UTC, BlackPoretsky commented on src/shared/ui/molecules/Button/ui/Button.tsx
> +      className={cn(st.button, (iconRight || iconLeft) && st["button--icon"])}
не понял, как это через classnames делать?

2024-02-27 07:33 UTC, BlackPoretsky commented on src/shared/ui/atoms/Text/Types/ITextProps.ts
> +  children: string
как по мне странно, что компонент Text может быть без текста предлагаю просто условие в button добавить, чтобы  он не создавал Text если children  undefined.

2024-02-28 17:04 UTC, AmyGrooove commented on src/shared/ui/molecules/Button/ui/Button.tsx
> +      className={cn(st.button, (iconRight || iconLeft) && st["button--icon"])}
> не понял, как это через classnames делать?

ну в плане
просто как вариант можно добавить в проект classnames (это библа)

2024-02-28 17:04 UTC, AmyGrooove commented on src/shared/ui/atoms/Text/Types/ITextProps.ts
> +  children: string
> как по мне странно, что компонент Text может быть без текста предлагаю просто условие в button добавить, чтобы он не создавал Text если children undefined.

а
я делбик
не тот тип смотрел

2024-02-28 19:47 UTC, merged